---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: date
  type: datetime
  label: date
  description: Date of the project
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: thumbnail
  label: Thumbnail
  type: file
  description: Thumbnail Image at 70 pixels by 70 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: test
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: test
pages:
- _projects/project-1.md
