---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - Shop
    - Restraurant
    - Hotel
    - Brand
    - House
    - Building
    - Products
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
  description: Project Category
- name: date
  type: datetime
  label: Date
  description: Date of the project
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: thumbnail
  label: Thumbnail
  type: file
  description: Thumbnail Image at 70 pixels by 70 pixels
  hidden: false
  default: ''
- name: client
  type: text
  config:
    required: true
  label: Client
- name: location
  type: text
  config:
    required: true
  label: Location
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: featured
  type: boolean
  label: Featured
  description: To show in front page
  default: false
- name: area
  type: text
  config:
    required: true
  label: Area
- name: leader
  type: text
  config:
    required: false
  label: Leader
- name: members
  type: text
  config:
    required: false
  label: Members
- name: construction
  type: text
  config:
    required: false
  label: Construction
  description: 施工单位
- name: constructor
  type: text
  config:
    required: false
  label: Constructor
  description: 施工团队
- name: construction_date
  type: datetime
  label: Construction Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- _projects/project-3.md
- _projects/project-2.md
- _projects/project-1.md
