---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: title_cn
  type: text
  config:
    required: true
  label: 名称
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - SHOP
    - HOTEL
    - HOUSE
    - OFFICE
    - RESTAURANT
    - BRANDING
    - BUILDING
    - PRODUCTS
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
  description: Project Category
- name: cover
  label: Cover
  type: file
  hidden: false
  default: ''
  description: 封面图
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: client
  type: text
  config:
    required: true
  label: Client
- name: client_cn
  type: text
  config:
    required: true
  label: 客户
- name: location
  type: text
  config:
    required: true
  label: Location
- name: location_cn
  type: text
  config:
    required: true
  label: 项目地点
- name: area
  type: text
  config:
    required: false
  label: Area
- name: designer
  type: text
  config:
    required: false
  label: Designer
  description: 设计师
- name: designer_cn
  type: text
  config:
    required: true
  label: 主设计师
- name: members
  type: text
  config:
    required: false
  label: Members
  description: 设计团队
- name: members_cn
  type: text
  config:
    required: false
  label: 设计团队
- name: construction
  type: text
  config:
    required: false
  label: Construction
  description: 施工单位
- name: construction_cn
  type: text
  config:
    required: false
  label: 施工单位
- name: constructor
  type: text
  config:
    required: false
  label: Constructor
  description: 施工团队
- name: constructor_cn
  type: text
  config:
    required: false
  label: 施工团队
- name: date
  type: datetime
  label: Date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
  description: 设计时间
- name: construction_date
  type: datetime
  label: Construction Date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  description: 施工时间
- name: featured
  type: boolean
  label: Featured
  description: To show in front page
  default: false
- name: tag
  type: tag_list
  default: []
  label: tag
  description: 商业分类
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: 内容描述
- name: description_cn
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: 描述
pages:
- _projects/ht-fitness-vi.md
- _projects/ht-fitness.md
- _projects/cs-house.md
- _projects/jh-house.md
- _projects/lin-house.md
- _projects/lin-hotel.md
- _projects/cdh-lighting.md
- _projects/hay.md
- _projects/one-one-vi.md
- _projects/sensorylab-shop.md
- _projects/project-3.md
- _projects/project-2.md
- _projects/project-1.md
- _projects/seerfashion-office.md
- _projects/mornfasion-vi.md
