---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: images
  type: image_gallery
  config: {}
  label: Images
