---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - Shop
    - Restraurant
    - Hotel
    - Brand
    - House
    - Building
    - Products
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
  description: Project Category
- name: date
  type: datetime
  label: Date
  description: Date of the project
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: thumbnail
  label: Thumbnail
  type: file
  description: Thumbnail Image at 70 pixels by 70 pixels
  hidden: false
  default: ''
- name: client
  type: text
  config:
    required: true
  label: Client
- name: location
  type: text
  config:
    required: true
  label: Location
- name: images
  type: image_gallery
  config: {}
  label: Images
pages:
- _projects/project-1.md
